kind: ConfigMap
apiVersion: v1
metadata:
  name: workshop-modules
data:
  modules.json: |
    {
      "modules": [
        {
          "name": "Build new functionality with Change Data Capture",
          "description": "In this module you discover how you can leverage Change Data Capture to build out new functionality with minimal impact on existing applications.",
          "tags": {
            "primary": [
              "#CDC",
              "#Kafka",
              "#Debezium",
              "#Camel-K",
              "#DevSpaces"
            ],
            "secondary": [
              "#hands-on"
            ]
          },
          "configMap": "module-cdc",
          "namespaces": ["globex-cdc-{{`{{ __user }}`}}"]          
        }
      ]
    }
