kind: ConfigMap
apiVersion: v1
metadata:
  name: module-camel
data:
  module-camel.json: |
    {
      "apiVersion": "argoproj.io/v1alpha1",
      "kind": "Application",
      "metadata": {
        "name": "{{ .Values.module.module_camel.name }}",
        "namespace": "{{ .Values.module.module_camel.namespace }}",
        "finalizers": [
          "resources-finalizer.argocd.argoproj.io/foreground"
        ]
      },
      "spec": {
        "destination": {
          "name": "",
          "namespace": "{{ .Values.module.module_camel.destination.namespace }}",
          "server": "https://kubernetes.default.svc"
        },
        "project": "default",
        "syncPolicy": {
          "automated": {
            "prune": false,
            "selfHeal": false
          }
        },
        "source": {
          "repoURL": "{{ .Values.module.module_camel.source.repoUrl }}",
          "targetRevision": "{{ .Values.module.module_camel.source.targetRevision }}",
          "path": "{{ .Values.module.module_camel.source.path }}",
          "helm": {
            "values": "\nminio:\n  minio:\n    accessKey: minio\n    secretKey: minio123\n    region: us-east-1\n  route:\n    host: minio-globex-camel-{{ .Values.variable.user }}.{{ .Values.openshift.domain }}\n\nkafka:\n  kafka:\n    namespace: globex-mw-{{ .Values.variable.user }}\n\namq-broker:\n  amq:\n    namespace: camel-common\n\nglobex-web:\n  globexStoreApp:\n    url: http://globex-store-app.globex-{{ .Values.variable.user }}:8080\n  activityTrackingService:\n    url: http://activity-tracking.globex-{{ .Values.variable.user }}:8080\n  recommendationEngine:\n    url: http://recommendation-engine.globex-{{ .Values.variable.user }}:8080\n  globexSupportUrl:\n    url: http://globex-support:80\n\n  sso:\n    url: \"https://sso.{{ .Values.openshift.domain }}/realms/globex-{{ .Values.variable.user }}\"\n    client: globex-web-gateway\n    logoutUri: https://globex-web-globex-camel-{{ .Values.variable.user }}.{{ .Values.openshift.domain }}/home\n\nmatrix-secret:\n  matrix:\n    namespace: camel-common\n    url: http://matrix-synapse.camel-common.svc.cluster.local:8008\n\nmatrix-integration:\n  deploy: false\n  rocketchat:\n    channel: globex-support-{{ .Values.variable.user }}\n\nglobex-support-integration:\n  deploy: false\n\ntranscript-integration:\n  deploy: false\n\n"
          }
        }
      }
    }